spring:
  datasource:
    url: jdbc:mysql://mysql57.rdsmt6qp16oti9n.rds.su.baidubce.com:3306/hap_user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: iiot_admin
    password: iiot_admin123